#!/bin/bash
set -eu -o pipefail
if [ $# -ne 1 ]
then
  echo "$0 <esp32-cam_IP>" >&2
  exit 2
fi
IP=$1
shift 1

flags=()
flags+=(-v) # be verbose
flags+=(--rtsp-transport=tcp)
#flags+=(--keep-open-pause=no)
#flags+=(--keep-open)
flags+=(--cache=no --no-cache)
flags+=(--profile=low-latency)
#flags+=(--demuxer-thread=no --demuxer-readahead-secs=0)
flags+=(--script="mpv.lua") # checks for stream position and reconnects if no change for 5s
#flags+=(--fs)
#flags+=(--network-timeout=10)
flags+=(--msg-level="all=info")
flags+=("rtsp://$IP:8554/mjpeg/2") # stream address

set -x
exec mpv "${flags[@]}"
