#!/bin/bash
set -eu -o pipefail
set -x

cd /opt/cam_view
source .env

function find_camera
{
  nmap -oG - -v -p "$port" "$netroot.0/24" \
    | grep "^Host: $netroot.[0-9]\+ ().*Ports: $port/" \
    | awk '{ print $2 }'
}


while sleep 5
do
  date
  if ping -c 4 -DO -W 3 "$preferred_ip"
  then
      time ./receive "$preferred_ip" || true
  else
    for ip in $(find_camera || continue)
    do
      time ./receive "$ip" || true
    done
  fi
done
