#!/bin/bash
set -eux -o pipefail

cd /opt/cam_view
source .env

function find_camera
{
  nmap -oG - -v -p "$port" "$netroot.0/24" \
    | grep "^Host: $netroot.[0-9]\+ ().*Ports: $port/" \
    | awk '{ print $2 }' \
    | sort -R \
    | head -1
}

while sleep 1
do
  date
  ip=$(find_camera || continue)
  time ./receive "$ip"
done
