- name: install app dependecies
  apt:
    state: latest
    name:
      - mpv
      - nmap

- name: create application directory
  file:
    path: /opt/cam_view
    state: directory

- name: create configuration file
  template:
    src: env.j2
    dest: /opt/cam_view/.env

- name: copy application
  copy:
    src: 'src/{{ item.file }}'
    dest: '/opt/cam_view/{{ item.file }}'
    mode: '{{ item.mode }}'
  with_items:
    - { file: run,     mode: '755' }
    - { file: receive, mode: '755' }
    - { file: mpv.lua, mode: '644' }
  notify:
    - enable autologin getty on tty1
