- name: create user for a service
  user:
    name: cam_view
    shell: /bin/bash
    state: present
    password_lock: yes

- name: copy config files
  copy:
    src: '{{ item }}'
    dest: /home/cam_view/
    owner: cam_view
    group: cam_view
  with_items:
    - .xinitrc
    - .bash_profile
  notify:
    - enable autologin getty on tty1
